"""Initial migration - all tables

Revision ID: 3d9883f1b5ed
Revises: 
Create Date: 2026-03-19 12:48:59.021044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9883f1b5ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('award_books', schema=None) as batch_op:
        batch_op.drop_index('idx_award_books_award_year')
        batch_op.drop_index('idx_award_books_category')
        batch_op.drop_index('idx_award_books_search')
        batch_op.create_index('idx_award_books_award_year_category', ['award_id', 'year', 'category'], unique=False)
        batch_op.create_index('idx_award_books_displayable_year', ['is_displayable', 'year'], unique=False)
        batch_op.create_index('idx_award_books_search_combined', ['title', 'author'], unique=False)
        batch_op.create_index(batch_op.f('ix_award_books_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_award_books_award_id'), ['award_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_award_books_is_displayable'), ['is_displayable'], unique=False)
        batch_op.create_index(batch_op.f('ix_award_books_isbn13'), ['isbn13'], unique=False)
        batch_op.create_index(batch_op.f('ix_award_books_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_award_books_verification_status'), ['verification_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_award_books_year'), ['year'], unique=False)

    with op.batch_alter_table('awards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_awards_name'), ['name'], unique=False)

    with op.batch_alter_table('book_metadata', schema=None) as batch_op:
        batch_op.create_index('idx_book_metadata_author', ['author'], unique=False)
        batch_op.create_index('idx_book_metadata_title', ['title'], unique=False)

    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.create_index('idx_search_history_session_created', ['session_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_history_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('user_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_categories_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('user_viewed_books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_viewed_books_isbn'), ['isbn'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_viewed_books_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_viewed_books_viewed_at'), ['viewed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_viewed_books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_viewed_books_viewed_at'))
        batch_op.drop_index(batch_op.f('ix_user_viewed_books_session_id'))
        batch_op.drop_index(batch_op.f('ix_user_viewed_books_isbn'))

    with op.batch_alter_table('user_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_categories_session_id'))

    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_history_created_at'))
        batch_op.drop_index('idx_search_history_session_created')

    with op.batch_alter_table('book_metadata', schema=None) as batch_op:
        batch_op.drop_index('idx_book_metadata_title')
        batch_op.drop_index('idx_book_metadata_author')

    with op.batch_alter_table('awards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_awards_name'))

    with op.batch_alter_table('award_books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_award_books_year'))
        batch_op.drop_index(batch_op.f('ix_award_books_verification_status'))
        batch_op.drop_index(batch_op.f('ix_award_books_title'))
        batch_op.drop_index(batch_op.f('ix_award_books_isbn13'))
        batch_op.drop_index(batch_op.f('ix_award_books_is_displayable'))
        batch_op.drop_index(batch_op.f('ix_award_books_award_id'))
        batch_op.drop_index(batch_op.f('ix_award_books_author'))
        batch_op.drop_index('idx_award_books_search_combined')
        batch_op.drop_index('idx_award_books_displayable_year')
        batch_op.drop_index('idx_award_books_award_year_category')
        batch_op.create_index('idx_award_books_search', ['title', 'author'], unique=False)
        batch_op.create_index('idx_award_books_category', ['category'], unique=False)
        batch_op.create_index('idx_award_books_award_year', ['award_id', 'year'], unique=False)

    # ### end Alembic commands ###
