"""Add Chinese language fields to book_metadata table

Revision ID: add_chinese_fields
Revises: 3d9883f1b5ed
Create Date: 2026-04-16 16:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_chinese_fields'
down_revision = '3d9883f1b5ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_zh', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('description_zh', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('details_zh', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('translated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_metadata', schema=None) as batch_op:
        batch_op.drop_column('translated_at')
        batch_op.drop_column('details_zh')
        batch_op.drop_column('description_zh')
        batch_op.drop_column('title_zh')
    # ### end Alembic commands ###
