"""Create all missing tables

Revision ID: create_all_missing_tables
Revises: add_csrf_tokens_table
Create Date: 2026-05-14 00:00:00.000000

说明：初始迁移 3d9883f1b5ed 仅包含 CREATE INDEX，未创建实际表结构。
本迁移文件补充创建 8 个缺失的表：
  - translation_cache（翻译缓存）
  - api_cache（API缓存）
  - system_config（系统配置）
  - weekly_reports（周报）
  - report_views（周报阅读记录）
  - user_behaviors（用户行为）
  - publishers（出版社）
  - new_books（新书）
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'create_all_missing_tables'
down_revision = 'add_csrf_tokens_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. translation_cache（翻译缓存表）
    op.create_table(
        'translation_cache',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_hash', sa.String(length=64), nullable=False),
        sa.Column('source_text', sa.Text(), nullable=False),
        sa.Column('source_lang', sa.String(length=10), nullable=False, server_default='en'),
        sa.Column('target_lang', sa.String(length=10), nullable=False, server_default='zh'),
        sa.Column('translated_text', sa.Text(), nullable=False),
        sa.Column('model_name', sa.String(length=100), server_default='glm-4.7-flash'),
        sa.Column('model_version', sa.String(length=50), nullable=True),
        sa.Column('quality_score', sa.Float(), nullable=True),
        sa.Column('usage_count', sa.Integer(), server_default='0'),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('source_hash', 'source_lang', 'target_lang', name='uix_translation_source_target'),
    )
    with op.batch_alter_table('translation_cache', schema=None) as batch_op:
        batch_op.create_index('idx_translation_lang_usage', ['source_lang', 'target_lang', 'usage_count'], unique=False)
        batch_op.create_index('idx_translation_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_cache_source_hash'), ['source_hash'], unique=False)

    # 2. api_cache（外部API缓存表）
    op.create_table(
        'api_cache',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('api_source', sa.String(length=50), nullable=False),
        sa.Column('request_key', sa.String(length=255), nullable=False),
        sa.Column('request_hash', sa.String(length=64), nullable=False),
        sa.Column('response_data', sa.Text(), nullable=False),
        sa.Column('status_code', sa.Integer(), server_default='200'),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('ttl_seconds', sa.Integer(), server_default='86400'),
        sa.Column('usage_count', sa.Integer(), server_default='0'),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('api_source', 'request_hash', name='uix_api_cache_source_hash'),
    )
    with op.batch_alter_table('api_cache', schema=None) as batch_op:
        batch_op.create_index('idx_api_cache_expiry', ['api_source', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_cache_api_source'), ['api_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_cache_request_key'), ['request_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_cache_request_hash'), ['request_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_cache_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_cache_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_cache_last_used_at'), ['last_used_at'], unique=False)

    # 3. system_config（系统配置表）
    op.create_table(
        'system_config',
        sa.Column('key', sa.String(length=100), nullable=False),
        sa.Column('value', sa.Text(), nullable=True),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('key'),
    )

    # 4. weekly_reports（每周畅销书报告表）
    op.create_table(
        'weekly_reports',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('report_date', sa.Date(), nullable=False),
        sa.Column('week_start', sa.Date(), nullable=False),
        sa.Column('week_end', sa.Date(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('top_changes', sa.Text(), nullable=True),
        sa.Column('featured_books', sa.Text(), nullable=True),
        sa.Column('view_count', sa.Integer(), server_default='0'),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('week_start', 'week_end', name='uix_weekly_report_week'),
    )
    with op.batch_alter_table('weekly_reports', schema=None) as batch_op:
        batch_op.create_index('idx_weekly_reports_date', ['report_date'], unique=False)
        batch_op.create_index('idx_weekly_reports_view_count', ['view_count'], unique=False)

    # 5. report_views（周报阅读记录表）
    op.create_table(
        'report_views',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('report_id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.String(length=64), nullable=False),
        sa.Column('viewed_at', sa.DateTime(), nullable=True),
        sa.Column('user_agent', sa.String(length=500), nullable=True),
        sa.Column('ip_address', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['report_id'], ['weekly_reports.id'], ),
    )
    with op.batch_alter_table('report_views', schema=None) as batch_op:
        batch_op.create_index('idx_report_views_report_session', ['report_id', 'session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_views_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_views_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_views_viewed_at'), ['viewed_at'], unique=False)

    # 6. user_behaviors（用户行为数据表）
    op.create_table(
        'user_behaviors',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.String(length=64), nullable=False),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('target_id', sa.String(length=100), nullable=True),
        sa.Column('target_type', sa.String(length=50), nullable=True),
        sa.Column('duration', sa.Integer(), nullable=True),
        sa.Column('user_agent', sa.String(length=500), nullable=True),
        sa.Column('ip_address', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('user_behaviors', schema=None) as batch_op:
        batch_op.create_index('idx_user_behaviors_session_event', ['session_id', 'event_type'], unique=False)
        batch_op.create_index('idx_user_behaviors_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_behaviors_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_behaviors_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_behaviors_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_behaviors_created_at'), ['created_at'], unique=False)

    # 7. publishers（出版社表）
    op.create_table(
        'publishers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('name_en', sa.String(length=200), nullable=False),
        sa.Column('website', sa.String(length=500), nullable=True),
        sa.Column('crawler_class', sa.String(length=100), nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true'),
        sa.Column('last_sync_at', sa.DateTime(), nullable=True),
        sa.Column('sync_count', sa.Integer(), server_default='0'),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name_en', name='uix_publisher_name_en'),
    )
    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.create_index('idx_publisher_active_sync', ['is_active', 'last_sync_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_publishers_name_en'), ['name_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_publishers_is_active'), ['is_active'], unique=False)

    # 8. new_books（新书表）
    op.create_table(
        'new_books',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('publisher_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=False),
        sa.Column('title_zh', sa.String(length=500), nullable=True),
        sa.Column('author', sa.String(length=300), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('description_zh', sa.Text(), nullable=True),
        sa.Column('isbn13', sa.String(length=13), nullable=True),
        sa.Column('isbn10', sa.String(length=10), nullable=True),
        sa.Column('cover_url', sa.String(length=500), nullable=True),
        sa.Column('cover_local', sa.String(length=255), nullable=True),
        sa.Column('category', sa.String(length=100), nullable=True),
        sa.Column('publication_date', sa.Date(), nullable=True),
        sa.Column('price', sa.String(length=50), nullable=True),
        sa.Column('page_count', sa.Integer(), nullable=True),
        sa.Column('language', sa.String(length=50), nullable=True),
        sa.Column('buy_links', sa.Text(), nullable=True),
        sa.Column('source_url', sa.String(length=500), nullable=True),
        sa.Column('is_verified', sa.Boolean(), server_default='false'),
        sa.Column('is_displayable', sa.Boolean(), server_default='true'),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ondelete='CASCADE'),
        sa.UniqueConstraint('publisher_id', 'isbn13', name='uix_publisher_isbn13'),
    )
    with op.batch_alter_table('new_books', schema=None) as batch_op:
        batch_op.create_index('idx_new_books_publisher_date', ['publisher_id', 'publication_date'], unique=False)
        batch_op.create_index('idx_new_books_category_display', ['category', 'is_displayable'], unique=False)
        batch_op.create_index('idx_new_books_search', ['title', 'author'], unique=False)
        batch_op.create_index(batch_op.f('ix_new_books_publisher_id'), ['publisher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_new_books_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_new_books_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_new_books_isbn13'), ['isbn13'], unique=False)
        batch_op.create_index(batch_op.f('ix_new_books_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_new_books_is_verified'), ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_new_books_is_displayable'), ['is_displayable'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 8. new_books
    with op.batch_alter_table('new_books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_new_books_is_displayable'))
        batch_op.drop_index(batch_op.f('ix_new_books_is_verified'))
        batch_op.drop_index(batch_op.f('ix_new_books_category'))
        batch_op.drop_index(batch_op.f('ix_new_books_isbn13'))
        batch_op.drop_index(batch_op.f('ix_new_books_author'))
        batch_op.drop_index(batch_op.f('ix_new_books_title'))
        batch_op.drop_index(batch_op.f('ix_new_books_publisher_id'))
        batch_op.drop_index('idx_new_books_search')
        batch_op.drop_index('idx_new_books_category_display')
        batch_op.drop_index('idx_new_books_publisher_date')
    op.drop_table('new_books')

    # 7. publishers
    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publishers_is_active'))
        batch_op.drop_index(batch_op.f('ix_publishers_name_en'))
        batch_op.drop_index('idx_publisher_active_sync')
    op.drop_table('publishers')

    # 6. user_behaviors
    with op.batch_alter_table('user_behaviors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_behaviors_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_behaviors_target_id'))
        batch_op.drop_index(batch_op.f('ix_user_behaviors_event_type'))
        batch_op.drop_index(batch_op.f('ix_user_behaviors_session_id'))
        batch_op.drop_index('idx_user_behaviors_created_at')
        batch_op.drop_index('idx_user_behaviors_session_event')
    op.drop_table('user_behaviors')

    # 5. report_views
    with op.batch_alter_table('report_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_views_viewed_at'))
        batch_op.drop_index(batch_op.f('ix_report_views_session_id'))
        batch_op.drop_index(batch_op.f('ix_report_views_report_id'))
        batch_op.drop_index('idx_report_views_report_session')
    op.drop_table('report_views')

    # 4. weekly_reports
    with op.batch_alter_table('weekly_reports', schema=None) as batch_op:
        batch_op.drop_index('idx_weekly_reports_view_count')
        batch_op.drop_index('idx_weekly_reports_date')
    op.drop_table('weekly_reports')

    # 3. system_config
    op.drop_table('system_config')

    # 2. api_cache
    with op.batch_alter_table('api_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_cache_last_used_at'))
        batch_op.drop_index(batch_op.f('ix_api_cache_expires_at'))
        batch_op.drop_index(batch_op.f('ix_api_cache_created_at'))
        batch_op.drop_index(batch_op.f('ix_api_cache_request_hash'))
        batch_op.drop_index(batch_op.f('ix_api_cache_request_key'))
        batch_op.drop_index(batch_op.f('ix_api_cache_api_source'))
        batch_op.drop_index('idx_api_cache_expiry')
    op.drop_table('api_cache')

    # 1. translation_cache
    with op.batch_alter_table('translation_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_cache_source_hash'))
        batch_op.drop_index('idx_translation_created')
        batch_op.drop_index('idx_translation_lang_usage')
    op.drop_table('translation_cache')

    # ### end Alembic commands ###
